name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:  # Allows manual triggering
env:
  PROJECT_FILE_PATH: BalatroUnsteamed.vcxproj
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat

    - name: Install Dependencies
      run: vcpkg\vcpkg.exe install detours:x64-windows

    - name: Integrate vcpkg with MSBuild
      run: vcpkg\vcpkg.exe integrate install

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=x64 /p:VcpkgTriplet=x64-windows ${{env.PROJECT_FILE_PATH}}

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: ${{ github.workspace }}\x64\Release\*  # Adjust path to your build output directory
        if-no-files-found: warn
        compression-level: 6
        overwrite: false
        include-hidden-files: false
